### ISSUE TITLE
Hard coded server display address?

### ISSUE THREAD

**Issue by prahjister** [jhdewitt/sltk#5]
Do i need to hard code this address? What address is this?

#define SERVER_DISPLAY_ADDRESS "0.0.0.0"
#define SERVER_DISPLAY_PORT "3210" //4001 // from client for displaying patterns
#define CLIENT_DISPLAY_PORT "4011" // to client

#define SERVER_CAMERA_PORT  "4002" // from client for image capture
#define CLIENT_CAMERA_PORT  "4012"

#define CLIENT_SERIAL_PORT  "4013"
#define SERVER_SERIAL_PORT  "4003" // from client for stepper motor control

**Comment by jhdewitt** [comment]
IP address configuration ideally would be from a file/argument but silly me decided back then it was a good idea to put them in the code like that since I was the only person using it then.

SERVER_DISPLAY_ADDRESS ought to be the address of the computer that is running sldisp. The ports are a mess, and need to be cleaned up. Will get started in GIMP to sketch out a diagram to make the connections easier to understand.

`0.0.0.0` or `127.0.0.1` should work to specify the local computer (open connection to own computer).

**Comment by jhdewitt** [comment]
this should cover the scope of this issue

https://github.com/jhdewitt/sltk/wiki/Networking-Notes#editing-network-configuration
